server:
  port: 10008
spring:

  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.glls.common.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置

# 输出 sql 日志
logging:
  level:
    com.glls.stock.mapper: DEBUG

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
#  registry:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      application: seata-server
#      group: SEATA_GROUP
#    type: nacos
  service:
    vgroup-mapping:
      stock-group: default